codemonkey_portfolio_homepage:
    pattern:  /
    defaults: { _controller: CodemonkeyPortfolioBundle:Default:index }

codemonkey_portfolio_about:
    pattern:  /about
    defaults: { _controller: CodemonkeyPortfolioBundle:Default:about }