homepage:
    pattern:  /{_locale}
    defaults: { _controller: CodemonkeyPortfolioBundle:Default:index, _locale: es }
    requirements:
            _locale: es|de|en

about:
    pattern:  /{_locale}/about
    defaults: { _controller: CodemonkeyPortfolioBundle:Default:about }
    requirements:
            _locale: es|de|en

contact:
    pattern:  /{_locale}/contact
    defaults: { _controller: CodemonkeyPortfolioBundle:Default:contact }
    requirements:
            _locale: es|de|en

posts:
    pattern:  /{_locale}/posts
    defaults: { _controller: CodemonkeyPortfolioBundle:Default:posts }
    requirements:
            _locale: es|de|en